server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Gère correctement les redirections SPA React
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Configuration de cache pour les images, CSS et JS (Optionnel mais recommandé)
    location ~* \.(?:ico|css|js|gif|png|jpe?g|svg|woff2?|ttf|webp|pdf)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public, no-transform";
    }
}
